### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by apdavison** [open-research/sumatra#201]
When I type smt list ,I get this exception.Kindly help me out
        

 _Imported from Bitbucket issue [215](https://bitbucket.org/apdavison/sumatra/issue/215),  created by ssubra32 on 01-28-2015 at 16:25, last modified: 01-28-2015 at 16:25_

**Comment by mattions** [comment]
This is due to Django 1.7.

We need to either port it to 1.7, or stop it to 1.6
https://github.com/open-research/sumatra/blob/master/setup.py#L61


More info here: 
https://docs.djangoproject.com/en/1.7/releases/1.7/#app-loading-refactor

According to Stackoverflow, we need to call `django.setup()` before the we do a call to the database:
http://stackoverflow.com/questions/22744949/runtime-errorapp-registry-isnt-ready-yet

**Comment by apdavison** [comment]
Duplicate of #199
